KTraining/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using KTraining.Models;

namespace KTraining.Controllers
{
    public class TestController : BaseController
    {
        // GET: Type test
        [Authorize(Roles = "Teacher")]
        public ActionResult Type()
        {
            return View();
        }

        //GET: Unsolved tests for student
        [Authorize(Roles = "Student")]
        [HttpGet]
        public ActionResult UnsolvedTests()
        {
            var student = this.studentService.GetStudentByAppUserId(this.User.Identity.GetUserId());
            var viewModel = new UnsolvedTestsViewModel
            {
                AutomaticTests = student.AutomaticTestsToSolve.ToList().OrderBy(x => x.Course.Name).ToList(),
                ManualTests = student.ManualTestsToSolve.ToList().OrderBy(x => x.Course.Name).ToList()
            };
            return View(viewModel);
        }

        [Authorize(Roles = "Student")]
        [HttpGet]
        public JsonResult CountUnsolvedTests()
        {
            var student = this.studentService.GetStudentByAppUserId(this.User.Identity.GetUserId());
            var count = student.AutomaticTestsToSolve.Count + student.ManualTestsToSolve.Count;
            return Json(count, JsonRequestBehavior.AllowGet);
        }

    }
}

KTraining/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - KTraining</title>
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("/Scripts/jquery-2.1.1.js")
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("KTraining", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Teacher"))
                        {
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
                                    Курсове <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li role="presentation">@Html.ActionLink("Вашите курсове", "GetAllCourses", "Course")</li>
                                    <li role="presentation">@Html.ActionLink("Kурсове", "Courses", "Course")</li>
                                    <li role="presentation">@Html.ActionLink("Завършени курсове", "CompletedTeacherCourses", "Course")</li>
                                    <li role="presentation"><a href="/Request/RequestsToJoin">Заявки за курсове <span class="badge notification req"></span></a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
                                        Тестове <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu" >
                                        <li role="presentation"><a href="/CheckManualTest/Tests">Тестове за проверяване <span class="badge notification ch-test"></span></a></li>
                                        <li role="presentation">@Html.ActionLink("Тестове", "Type", "Test")</li>
                                        <li role="presentation">@Html.ActionLink("Изпитване", "SelectTest", "TestExamination")</li>
                                        <li role="presentation"></li>
                                    </ul>
                            </li>

                            <li>@Html.ActionLink("Теми", "Topics", "Topic")</li>
                        }

                        if (User.IsInRole("Student"))
                        {

                            <li><a href="/Mark/Marks">Оценки <span class="badge notification unsMarks"></span></a></li>
                            <li role="presentation"></li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
                                    Курсове <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li role="presentation">@Html.ActionLink("Вашите курсове", "StudentCourses", "Course")</li>
                                    <li role="presentation">@Html.ActionLink("Kурсове", "Courses", "Course")</li>
                                    <li role="presentation">@Html.ActionLink("Завършени курсове", "CompletedStudentCourses", "Course")</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;">
                                    Тестове <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li role="presentation"><a href="/Test/UnsolvedTests">Тестове за решаване <span class="badge slvd-tests notification"></span></a></li>
                                    <li role="presentation"><a href="/SolvedTest/SolvedTests">Решени тестове</a></li>
                                </ul>
                            </li>
                        }


                    }
                    <li id="search-li" >
                        <form action="/Search/Search" method="get" class="form-inline">
                            <div class="form-group">
                                <input class="form-control search-input" type="text" name="q" placeholder="Търсене" />
                            </div>
                            <div class="form-group">
                                <input value="Търси" type="submit" class="btn btn-default btn-sm" />
                            </div>
                        </form>
                    </li>
                </ul>        
                @Html.Partial("_LoginPartial")
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -KTraining</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
        <script src="~/Scripts/jquery-ui-1.11.1.js"></script>
     <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/prThis.js"></script>

    <script src="~/Scripts/fileinput.js"></script>
    <script>
        if("@User.IsInRole("Student")"==="True")
        {
            $.ajax({
                type: "GET",
                url: "/Mark/CountUnseenMarks",
                traditional: true,
                success: function (data) {
                    if (unescape(data).toString() === "0")
                    {
                        $(".unsMarks").addClass("hidden");
                    }
                    else
                    {
                        $(".unsMarks").html(unescape(data));
                        $(".unsMarks").removeClass("hidden");
                    }

                }
            });

            $.ajax({
                type: "GET",
                url: "/Test/CountUnsolvedTests",
                traditional: true,
                success: function (data) {
                    if (unescape(data).toString() === "0") {
                        $(".slvd-tests").addClass("hidden");
                    }
                    else {
                        $(".slvd-tests").html(unescape(data));
                        $(".slvd-tests").removeClass("hidden");
                    }

                }
            });
        }
        if("@User.IsInRole("Teacher")"==="True")
        {
            $.ajax({
                type: "GET",
                url: "/Request/CountRequestsToJoin",
                traditional: true,
                success: function (data) {
                    if (unescape(data).toString() === "0")
                    {
                        $(".req").addClass("hidden");
                    }
                    else
                    {
                        $(".req").html(unescape(data));
                        $(".req").removeClass("hidden");
                    }

                }
            });

            $.ajax({
                type: "GET",
                url: "/CheckManualTest/CountTests",
                traditional: true,
                success: function (data) {
                    if (unescape(data).toString() === "0") {
                        $(".ch-test").addClass("hidden");
                    }
                    else {
                        $(".ch-test").html(unescape(data));
                        $(".ch-test").removeClass("hidden");
                    }

                }
            });
        }
    </script>
</body>
</html>
<style>
    #search-li {
      padding-top:3px;
      padding-left:30px;
    }
    .search-input {
        width: 290px !important;
        max-width:400px !important;
    }
    .notification{
        background-color:#f7a1a1;
    }
</style>